on:
  push:
    tags:
    - 'v*'

name: Upload Kubernetes files to aliyun registry

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download files
        run: |
          echo "KUBE_VERSION=${GITHUB_REF##*/}"
          . ./version/${GITHUB_REF##*/}.sh
          . download_kube.sh

      - name: Login to registry.aliyuncs.com
        uses: docker/login-action@v1
        with:
          registry: registry.aliyuncs.com
          username: ${{ secrets.GITLAB_USERNAME }}
          password: ${{ secrets.GITLAB_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: /tmp/.kubei/${{ env.KUBE_VERSION }}
          file: ./docker/Dockerfile
          push: true
          tags: registry.aliyuncs.com/kubebin/kube-files:${{ env.KUBE_VERSION }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
